### PR TITLE
Python speedfix2

### PR DESCRIPTION
**Pull request by MichaelCurrie**
This commit is the improved PR #68 .

I can't figure out how to get the zip commits to not appear here, so that both the zipfiles and python_speedfix2 branches just show their respective commits relative to master.

Instead, as you can see below, the commits below include those for zipfiles.  Perhaps if zipfiles is merged with master, those commits will disappear here.

### CODE REVIEW

**Comment by Ichoran** [comment]
Can you rebase on master now that I've merged zipfiles?  (Don't bother closing the PR, just rebase and push -f.)

**Comment by MichaelCurrie** [comment]
OK done:

```
git checkout master
git pull
git checkout python_speedfix2
git rebase master
git push -f
```

This PR should pass the Travis-CI tests.  @Ichoran please merge if you don't have any code objections and if the CI tests pass.

**Comment by Ichoran** [comment]
Looks like 3.4 is still grumpy?

**Comment by MichaelCurrie** [comment]
Yes, I'll work on this.  Don't merge yet :)

**Comment by MichaelCurrie** [comment]
After no success duplicating the issue, I just asked Travis-CI to re-run the 3.4 job with the same commit and it worked this time.  I suspect this is because the odict representation of your 90 worms is not necessarily getting saved in the same order each time, and so the file comparison is saying the saved files are not identical.  I will write more unit tests on this topic.  But guaranteeing identical save files is really an extra, nice-to-have feature anyway, and another PR for another day.  This one can be merged.

**Pull request merged**
