### PR TITLE
Reorg for code

### PR DESCRIPTION
**Pull request by Ichoran**
Reorganized the project structure to be better suited for code development as well as hosting discussion summaries and the like.

### CODE REVIEW

**Comment by Ichoran** [comment]
@aexbrown - I've reorganized things a bit and added a MIT license for code.  Can you check things over and commit if it seems okay?

**Comment by Ichoran** [comment]
Also, when merged you can close the "License for Code" issue I raised (if you want, or I'll take care of it when I notice it's merged).

**Comment by MichaelCurrie** [comment]
This seems like a reorganization of existing content and a modification of the license (rendered somewhat moot by my changing of the license from CC0 to MIT with this impolite "push"-style commit cd9c98ec7a4158c9fcc781bab430fa1af7a7e60d back on 27 October, but I still like your version better since it has more information at the top beyond the MIT license boilerplate.)

I'm going to resolve the conflicts and then merge this unless there are any obligations!

**Comment by Ichoran** [comment]
No obligations.  No objections either.

**Comment by MichaelCurrie** [comment]
Haha.  My autocorrect working overtime.

**Pull request merged**
