### PR TITLE
Python speed fix

### PR DESCRIPTION
**Pull request by MichaelCurrie**
Handles issue #55

### CODE REVIEW

**Comment by Ichoran** [comment]
Can we please not check in a gigantic WCON file that is mostly spaces and has errors in its units?  The supposed "time" is actually frame number, I think.  And the X and Y units seem to be microns, not millimeters.  Or maybe they're pixels; I didn't check carefully enough to be sure.  But they're certainly not millimeters.

The code itself looks good, and it's fine to use this as a test file for internal testing, but this isn't the kind of thing that should go into the standard distribution.  (I also don't think it's a good idea to make someone pull down 50 MB just to clone the repository.)  If you want to include a speed test, I think you should programmatically create the data structure, then write it, then read it.  (And then maybe delete it.)

**Comment by MichaelCurrie** [comment]
"mostly spaces" is because I selected "pretty print" as the JSON output option, so it is more human readable.  Good point about time being a frame number, and about the units being microns.  This file was created from a Schafer corpus file; I will reconvert it with corrections.

I can't programatically or "procedurally" create this data, because it isn't random, but I agree it would be nice not to have this in the repository.  So I've rolled back the commits (rather than reverting them, which would still have kept the .git file bloated), and I'll instead put this file on Google Drive and have the Travis CI code download the files.

**Comment by MichaelCurrie** [comment]
(Removed this comment; it now appears at Pull Request https://github.com/openworm/tracker-commons/pull/66)

**Comment by MichaelCurrie** [comment]
(Removed this comment; it now appears at Pull Request https://github.com/openworm/tracker-commons/pull/66)

**Comment by Ichoran** [comment]
Can you put the zip stuff in some other PR?  This is mixing too many concerns at once.

**Comment by Ichoran** [comment]
Actually, we've got three things here at the same time: (1) speed fixes; (2) unit multipliers; (3) zip files.  These should be three separate PRs so the issues in each can be worked out independently.  69e5a53 was the last of the speed fix commits, I think.

**Comment by MichaelCurrie** [comment]
@Ichoran, my Git Fu is too weak for that.  Can you tell me how?  Let's start with moving all the commits after 2608333 to a new branch, we'll call `unit_multipliers`.

I did:

```
cd ~/github
git clone git@github.com:OpenWorm/tracker-commons
cd tracker-commons
git checkout python_speedfix
git branch unit_multipliers
git reset --hard 2608333
git checkout unit_multipliers
```

So now all commits after 2608333 are on the `unit_multipliers` branch.  But, when I try `git push` I get:

```
ubuntu@ip-172-31-9-94:~/github/tracker-commons$ git push
To git@github.com:OpenWorm/tracker-commons
 ! [rejected]        python_speedfix -> python_speedfix (non-fast-forward)
error: failed to push some refs to 'git@github.com:OpenWorm/tracker-commons'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by Ichoran** [comment]
Don't you want to reset to `69e5a53` (Iast commit before units rather than first after)?

Anyway, I think you just need a `git push -f python_speedfix`.

You could also try to rework the branches to be independent using `git rebase --onto master python_speedfix unit_multipliers`, but since I don't see any reason not to merge `python_speedfix`, you could just wait until that's merged and simply rebase unit_multipliers onto the new master.

Oh, and it looks like this branch is behind master too, so you should probably `git rebase master` on `python_speedfix` before doing anything else.

**Comment by MichaelCurrie** [comment]
@Ichoran, thanks for the tip about `-f`, and about needing to use one commit prior (i.e. 69e5a53).  So, I needed to do the following:

```
# Clone the repository
cd ~/github
git clone git@github.com:OpenWorm/tracker-commons
cd tracker-commons

# Stop python_speedfix at 69e5a53 and put all subsequent commits on the unit_multipliers branch
git checkout python_speedfix
git branch unit_multipliers
git reset --hard 69e5a53
git push -f origin python_speedfix

# Stop unit_multipliers at d80ddfe and put all subsequent commits on the zipfiles branch
git checkout unit_multipliers
git branch zipfiles
git reset --hard d80ddfe
git push -f origin unit_multipliers

# Stop zipfiles at dcf337b and put all subsequent commits on the python_speedfix2 branch
git checkout zipfiles
git branch python_speedfix2
git reset --hard dcf337b
git push -f origin zipfiles

# Push the remaining changes on the python_speedfix2 branch to remote
git checkout python_speedfix2
git push -f origin python_speedfix2
```

I didn't do `git rebase master` on `python_speedfix` but apparently there are no conflicts with master so even though it's behind I think it should merge okay.

**Comment by MichaelCurrie** [comment]
OK I have separated the other issues out into separate pull requests, and the tests pass.  @Ichoran  please merge if acceptable.

**Pull request merged**
