### PR TITLE
Zip files

### PR DESCRIPTION
**Pull request by MichaelCurrie**
Handles https://github.com/openworm/tracker-commons/issues/59 for Python, including tests.

### CODE REVIEW

**Comment by Ichoran** [comment]
Does this also need a rebase to get tests passing?

**Comment by MichaelCurrie** [comment]
I think the way to get this passing is to merge #68, which has this PR as its base.

But we can't do that yet as #68 is passing on only 2 out of the 3 versions of Python we test.  Fixing that now...

**Comment by Ichoran** [comment]
Can you please close this and rebase onto master, then open a PR to merge into master?  This way we'll have a linear series of improvements to master instead of a stack going forward and backward.

**Comment by MichaelCurrie** [comment]
OK I will do this, thanks

**Pull request closed without merging**
