### PR TITLE
Improved discussion of custom features in documentation.

### PR DESCRIPTION
**Pull request by Ichoran**

### CODE REVIEW

**Comment by Ichoran** [comment]
@JimHokanson - Can you check to see whether this resolves https://github.com/openworm/tracker-commons/issues/94 in your opinion and merge if so?

@MichaelCurrie - Feel free to jump in if you see anything that needs improvement.

**Comment by MichaelCurrie** [comment]
Plate features make more sense now, and I see there was a typo fix too.  Looks good to me.

**Comment by MichaelCurrie** [comment]
I'm going to be bold and merge this.  Jim feel free to jump in and add more comments if you think more needs to be done.

**Comment by JimHokanson** [comment]
@Ichoran 
My apologies on missing this. It looks much better. Thanks.

**Pull request merged**
