### PR TITLE
Octave branch

### PR DESCRIPTION
**Pull request by cheelee**
Skeleton prototype. Content with the branch are orthogonal to the rest of the code base.

### CODE REVIEW

**Comment by Ichoran** [comment]
Looks like a reasonable start.  Matlab uses single quotes for strings, though.  Maybe you should switch over if you intend this to be a drop-in replacement or nearly so?

**Comment by cheelee** [comment]
I'll try. Currently I have no means to test this against a licensed implementation of Matlab. My plan is to try and minimize the known octave vs matlab incompatibilities. I can at least make sure that single quoted strings will work correctly for octave implementations. I noticed there is a part when dealing with JSON literals that nested double-quotes inside single-quotes, so I kinda need to figure out if that's gonna be an issue with matlab. So far it does not appear to be a problem with octave.

**Comment by Ichoran** [comment]
I think just using `'this'` instead of `"this"` for strings should do the trick.  Oh, and also `% this is a comment` but `# this is not` in Matlab.

Those are the two most annoying trivial yet widespread differences in syntax.

**Comment by cheelee** [comment]
Just updating the pull request with the latest orthogonal changes (double-to-single quotes), with the understanding that we'd still need to resolve the current python failures before doing a proper merge. I've also changed the octave folder structure a little ... the driver code is now in examples, and a stub folder for tests has been created.

Thanks @Ichoran for the suggestions! Very painless changes to make, and avoids future headache for when we try this with Matlab :)

**Comment by cheelee** [comment]
Just an orthogonal comment on Travis-CI testing against Octave ... it would appear there are some apt-get white-listing issues that have not yet been resolved:
https://github.com/travis-ci/apt-source-whitelist/issues/53

**Comment by Ichoran** [comment]
Maybe it will be okay on Semaphore if Travis makes it awkward.

**Comment by cheelee** [comment]
Am not familiar with Semaphore, but I can take a look. Is it also an automatic CI feature linked with Github the way Travis-CI is?

**Comment by Ichoran** [comment]
Yes.  I've already got it running (on my Semaphore account).  If you write some tests, I'll try linking it in.  I think you could probably have your own Semaphore account and have it run different tests?  I'm not sure.

**Comment by cheelee** [comment]
Cool, I'll check it out, thanks! I'll first need to figure out how test results are semantically interpreted. With Python it's simply an assert, not sure how that's done in Octave/Matlab yet hehe. I'll take a peek at this over the weekend ... there are some pretty straightforward tests that are already exercised by main.m (like the two comparison tests on dummy WCON strings). 

Of course the equality function as currently implemented is merely skin-deep, I'm of the opinion true equality for WCON requires both data objects to be converted to their canonical forms first prior to comparison. 

I think @JimHokanson is gonna take a deeper look at our desired WCON interface to sort things out before we commit to something firm, so I'm probably getting ahead of myself here.

**Comment by Ichoran** [comment]
That's how I do testing in Scala--at the WCON object level, not at the JSON level.

**Pull request merged**
